# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    gaps_out = 3
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
    enabled = yes
    # Define the missing 'smoothOut' bezier curve
    bezier = smoothOut, 0.25, 0.1, 0.25, 1

    animation = borderangle, 1, 40, linear, loop
    animation = specialWorkspace, 1, 5, smoothOut, slide
}
